services:
  nestjs:
    build: containers/nestjs
    image: nestjs
    container_name: nestjs
    restart: on-failure
    depends_on:
      - db
    ports:
      - "3000:3000"
    # networks:
    #   - transcendence

  db:
    image: postgres:alpine
    container_name: db
    env_file: .env
    # networks:
    #   - transcendence
    # Use to manually inspect the db
    ports:
      - "5432:5432"

# networks:
#   transcendence:
#     name: transcendence
