services:
  nestjs:
    build: containers/nestjs
    image: nestjs
    container_name: nestjs
    init: true # Prevents from waiting on 10s timeout on shutdown
    restart: on-failure
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: postgres:alpine
    container_name: db
    env_file: .env
    ports: # Use to manually inspect the db
      - "5432:5432"
