services:
  nestjs:
    build: containers/nestjs
    image: nestjs
    container_name: nestjs
    restart: on-failure
    # networks:
    #   - transcendence
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: db
    env_file: .env
    # networks:
    #   - transcendence
    # ports:
    #   - "5432:5432"

# networks:
#   transcendence:
#     name: transcendence
