services:
  nestjs:
    build: containers/nestjs
    image: nestjs
    container_name: nestjs
    init: true # Prevents waiting on 10s timeout on shutdown
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - ./containers/nestjs/:/nestjs/code/
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: db
    env_file: .env
    ports: # Use to manually inspect the db
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
